package agents

import "time"

// AgentConfig captures runtime settings for an ADK agent instance.
type AgentConfig struct {
	Type                 AgentType
	Name                 string
	Description          string
	AIProvider           string
	Model                string
	Tools                []string
	OutputKey            string
	SystemPromptTemplate string

	MaxToolCalls      int
	MaxThinkingTokens int
	TimeoutPerTool    time.Duration
	TotalTimeout      time.Duration
	MaxCostPerRun     float64
}

// DefaultAgentConfigs aligns with the phase 7 plan for agent limits and prompts.
var DefaultAgentConfigs = map[AgentType]AgentConfig{
	AgentMarketAnalyst: {
		Type:                 AgentMarketAnalyst,
		Name:                 "MarketAnalyst",
		Description:          "Technical analyst focusing on price action and indicators",
		Tools:                ToolsForAgent(AgentMarketAnalyst),
		OutputKey:            "market_analysis",
		SystemPromptTemplate: "agents/market_analyst",
		MaxToolCalls:         25,
		MaxThinkingTokens:    4000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         2 * time.Minute,
		MaxCostPerRun:        0.10,
	},
	AgentSMCAnalyst: {
		Type:                 AgentSMCAnalyst,
		Name:                 "SMCAnalyst",
		Description:          "Smart Money Concepts analyst spotting liquidity and structure",
		Tools:                ToolsForAgent(AgentSMCAnalyst),
		OutputKey:            "smc_analysis",
		SystemPromptTemplate: "agents/smc_analyst",
		MaxToolCalls:         15,
		MaxThinkingTokens:    4000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.10,
	},
	AgentSentimentAnalyst: {
		Type:                 AgentSentimentAnalyst,
		Name:                 "SentimentAnalyst",
		Description:          "Sentiment analyst aggregating news and social data",
		Tools:                ToolsForAgent(AgentSentimentAnalyst),
		OutputKey:            "sentiment_analysis",
		SystemPromptTemplate: "agents/sentiment_analyst",
		MaxToolCalls:         10,
		MaxThinkingTokens:    2000,
		TimeoutPerTool:       15 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentOnChainAnalyst: {
		Type:                 AgentOnChainAnalyst,
		Name:                 "OnChainAnalyst",
		Description:          "On-chain analyst evaluating flows and supply",
		Tools:                ToolsForAgent(AgentOnChainAnalyst),
		OutputKey:            "onchain_analysis",
		SystemPromptTemplate: "agents/onchain_analyst",
		MaxToolCalls:         10,
		MaxThinkingTokens:    2000,
		TimeoutPerTool:       15 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentCorrelationAnalyst: {
		Type:                 AgentCorrelationAnalyst,
		Name:                 "CorrelationAnalyst",
		Description:          "Cross-market correlation analyst",
		Tools:                ToolsForAgent(AgentCorrelationAnalyst),
		OutputKey:            "correlation_analysis",
		SystemPromptTemplate: "agents/correlation_analyst",
		MaxToolCalls:         8,
		MaxThinkingTokens:    3000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentMacroAnalyst: {
		Type:                 AgentMacroAnalyst,
		Name:                 "MacroAnalyst",
		Description:          "Macro analyst covering economic events",
		Tools:                ToolsForAgent(AgentMacroAnalyst),
		OutputKey:            "macro_analysis",
		SystemPromptTemplate: "agents/macro_analyst",
		MaxToolCalls:         8,
		MaxThinkingTokens:    3000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentOrderFlowAnalyst: {
		Type:                 AgentOrderFlowAnalyst,
		Name:                 "OrderFlowAnalyst",
		Description:          "Order flow analyst reading tape and imbalance",
		Tools:                ToolsForAgent(AgentOrderFlowAnalyst),
		OutputKey:            "orderflow_analysis",
		SystemPromptTemplate: "agents/order_flow_analyst",
		MaxToolCalls:         12,
		MaxThinkingTokens:    3000,
		TimeoutPerTool:       5 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentDerivativesAnalyst: {
		Type:                 AgentDerivativesAnalyst,
		Name:                 "DerivativesAnalyst",
		Description:          "Derivatives analyst tracking options and gamma",
		Tools:                ToolsForAgent(AgentDerivativesAnalyst),
		OutputKey:            "derivatives_analysis",
		SystemPromptTemplate: "agents/derivatives_analyst",
		MaxToolCalls:         10,
		MaxThinkingTokens:    3000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.05,
	},
	AgentStrategyPlanner: {
		Type:                 AgentStrategyPlanner,
		Name:                 "StrategyPlanner",
		Description:          "Planner synthesizing agent outputs into a trade plan",
		Tools:                ToolsForAgent(AgentStrategyPlanner),
		OutputKey:            "trade_plan",
		SystemPromptTemplate: "agents/strategy_planner",
		MaxToolCalls:         8,
		MaxThinkingTokens:    6000,
		TimeoutPerTool:       5 * time.Second,
		TotalTimeout:         time.Minute,
		MaxCostPerRun:        0.15,
	},
	AgentRiskManager: {
		Type:                 AgentRiskManager,
		Name:                 "RiskManager",
		Description:          "Risk manager validating trades and sizing positions",
		Tools:                ToolsForAgent(AgentRiskManager),
		OutputKey:            "risk_assessment",
		SystemPromptTemplate: "agents/risk_manager",
		MaxToolCalls:         5,
		MaxThinkingTokens:    2000,
		TimeoutPerTool:       3 * time.Second,
		TotalTimeout:         30 * time.Second,
		MaxCostPerRun:        0.03,
	},
	AgentExecutor: {
		Type:                 AgentExecutor,
		Name:                 "Executor",
		Description:          "Executor responsible for placing and managing orders",
		Tools:                ToolsForAgent(AgentExecutor),
		OutputKey:            "execution_result",
		SystemPromptTemplate: "agents/executor",
		MaxToolCalls:         3,
		MaxThinkingTokens:    1500,
		TimeoutPerTool:       3 * time.Second,
		TotalTimeout:         30 * time.Second,
		MaxCostPerRun:        0.03,
	},
	AgentPositionManager: {
		Type:                 AgentPositionManager,
		Name:                 "PositionManager",
		Description:          "Position manager monitoring live trades",
		Tools:                ToolsForAgent(AgentPositionManager),
		OutputKey:            "position_update",
		SystemPromptTemplate: "agents/position_manager",
		MaxToolCalls:         5,
		MaxThinkingTokens:    2000,
		TimeoutPerTool:       5 * time.Second,
		TotalTimeout:         45 * time.Second,
		MaxCostPerRun:        0.03,
	},
	AgentSelfEvaluator: {
		Type:                 AgentSelfEvaluator,
		Name:                 "SelfEvaluator",
		Description:          "Self evaluator reviewing performance",
		Tools:                ToolsForAgent(AgentSelfEvaluator),
		OutputKey:            "evaluation_report",
		SystemPromptTemplate: "agents/self_evaluator",
		MaxToolCalls:         10,
		MaxThinkingTokens:    4000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         90 * time.Second,
		MaxCostPerRun:        0.05,
	},
	AgentOpportunitySynthesizer: {
		Type:                 AgentOpportunitySynthesizer,
		Name:                 "OpportunitySynthesizer",
		Description:          "Synthesizes multi-dimensional analysis into actionable opportunity signals",
		Tools:                ToolsForAgent(AgentOpportunitySynthesizer),
		OutputKey:            "opportunity_decision",
		SystemPromptTemplate: "agents/opportunity_synthesizer",
		MaxToolCalls:         2,
		MaxThinkingTokens:    3000,
		TimeoutPerTool:       5 * time.Second,
		TotalTimeout:         30 * time.Second,
		MaxCostPerRun:        0.05,
	},
	AgentPortfolioArchitect: {
		Type:                 AgentPortfolioArchitect,
		Name:                 "PortfolioArchitect",
		Description:          "Designs diversified portfolio strategies based on capital, risk tolerance, and market conditions",
		Tools:                ToolsForAgent(AgentPortfolioArchitect),
		OutputKey:            "portfolio_strategy",
		SystemPromptTemplate: "agents/portfolio_architect",
		MaxToolCalls:         15,
		MaxThinkingTokens:    5000,
		TimeoutPerTool:       10 * time.Second,
		TotalTimeout:         2 * time.Minute,
		MaxCostPerRun:        0.10,
	},
}
