package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"prometheus/internal/api/graphql/generated"
	"prometheus/internal/api/graphql/middleware"
	"prometheus/internal/domain/user"
	authService "prometheus/internal/services/auth"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input generated.RegisterInput) (*generated.AuthResponse, error) {
	// Call auth service
	authInput := authService.RegisterInput{
		Email:     input.Email,
		Password:  input.Password,
		FirstName: input.FirstName,
		LastName:  input.LastName,
	}

	result, err := r.AuthService.Register(ctx, authInput)
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	// Set HTTP-only cookie with JWT token
	if err := middleware.SetAuthCookie(ctx, result.Token); err != nil {
		return nil, fmt.Errorf("failed to set auth cookie: %w", err)
	}

	return &generated.AuthResponse{
		Token: result.Token,
		User:  result.User,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input generated.LoginInput) (*generated.AuthResponse, error) {
	// Call auth service
	authInput := authService.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	}

	result, err := r.AuthService.Login(ctx, authInput)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	// Set HTTP-only cookie with JWT token
	if err := middleware.SetAuthCookie(ctx, result.Token); err != nil {
		return nil, fmt.Errorf("failed to set auth cookie: %w", err)
	}

	return &generated.AuthResponse{
		Token: result.Token,
		User:  result.User,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Clear auth cookie
	if err := middleware.ClearAuthCookie(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	// Get user from context (set by auth middleware)
	usr := middleware.UserFromContext(ctx)
	if usr == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	return usr, nil
}
