package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/json"
	"fmt"
	"prometheus/internal/api/graphql/generated"
	"prometheus/internal/api/graphql/middleware"
	"prometheus/internal/domain/strategy"
	"prometheus/internal/domain/user"
	strategyService "prometheus/internal/services/strategy"
	"prometheus/pkg/relay"

	"github.com/google/uuid"
)

// buildStrategyConnection is a helper function to build GraphQL connection with scopes and filters
// This avoids code duplication between UserStrategies and Strategies resolvers
func buildStrategyConnection(
	items []*strategy.Strategy,
	totalCount int,
	params relay.PaginationParams,
	offset int,
	scopeCounts map[string]int,
) (*generated.StrategyConnection, error) {
	// Build relay connection
	conn, err := relay.NewConnection(items, totalCount, params, offset)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection: %w", err)
	}

	// Convert to GraphQL types
	edges := make([]*generated.StrategyEdge, len(conn.Edges))
	for i, edge := range conn.Edges {
		edges[i] = &generated.StrategyEdge{
			Node:   edge.Node,
			Cursor: edge.Cursor,
		}
	}

	// Build scopes with counts
	scopeDefs := getStrategyScopeDefinitions()
	scopes := make([]*generated.Scope, len(scopeDefs))
	for i, scopeDef := range scopeDefs {
		scopes[i] = &generated.Scope{
			ID:    scopeDef.ID,
			Name:  scopeDef.Name,
			Count: scopeCounts[scopeDef.ID],
		}
	}

	// Build filters from definitions
	filterDefs := getStrategyFilterDefinitions()
	filters := make([]*generated.Filter, len(filterDefs))
	for i, filterDef := range filterDefs {
		options := make([]*generated.FilterOption, len(filterDef.Options))
		for j, opt := range filterDef.Options {
			options[j] = &generated.FilterOption{
				Value: opt.Value,
				Label: opt.Label,
			}
		}

		filters[i] = &generated.Filter{
			ID:           filterDef.ID,
			Name:         filterDef.Name,
			Type:         generated.FilterType(filterDef.Type),
			Options:      options,
			DefaultValue: filterDef.DefaultValue,
			Placeholder:  filterDef.Placeholder,
		}
	}

	return &generated.StrategyConnection{
		Edges: edges,
		PageInfo: &generated.PageInfo{
			HasNextPage:     conn.PageInfo.HasNextPage,
			HasPreviousPage: conn.PageInfo.HasPreviousPage,
			StartCursor:     conn.PageInfo.StartCursor,
			EndCursor:       conn.PageInfo.EndCursor,
		},
		TotalCount: conn.TotalCount,
		Scopes:     scopes,
		Filters:    filters,
	}, nil
}

// CreateStrategy is the resolver for the createStrategy field.
func (r *mutationResolver) CreateStrategy(ctx context.Context, userID uuid.UUID, input generated.CreateStrategyInput) (*strategy.Strategy, error) {
	// Parse target allocations if provided
	var targetAllocations []byte
	if input.TargetAllocations != nil {
		data, err := json.Marshal(input.TargetAllocations)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal target allocations: %w", err)
		}
		targetAllocations = data
	}

	params := strategyService.CreateStrategyParams{
		UserID:             userID,
		Name:               input.Name,
		Description:        input.Description,
		AllocatedCapital:   input.AllocatedCapital,
		MarketType:         input.MarketType,
		RiskTolerance:      input.RiskTolerance,
		RebalanceFrequency: input.RebalanceFrequency,
		TargetAllocations:  targetAllocations,
	}

	return r.StrategyService.CreateStrategy(ctx, params)
}

// UpdateStrategy is the resolver for the updateStrategy field.
func (r *mutationResolver) UpdateStrategy(ctx context.Context, id uuid.UUID, input generated.UpdateStrategyInput) (*strategy.Strategy, error) {
	// Parse target allocations if provided
	var targetAllocations []byte
	if input.TargetAllocations != nil {
		data, err := json.Marshal(input.TargetAllocations)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal target allocations: %w", err)
		}
		targetAllocations = data
	}

	// Build update params
	params := strategyService.UpdateStrategyParams{
		Name:               input.Name,
		Description:        input.Description,
		RiskTolerance:      (*strategy.RiskTolerance)(input.RiskTolerance),
		RebalanceFrequency: (*strategy.RebalanceFrequency)(input.RebalanceFrequency),
		TargetAllocations:  targetAllocations,
	}

	return r.StrategyService.UpdateStrategy(ctx, id, params)
}

// PauseStrategy is the resolver for the pauseStrategy field.
func (r *mutationResolver) PauseStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	return r.StrategyService.PauseStrategy(ctx, id)
}

// ResumeStrategy is the resolver for the resumeStrategy field.
func (r *mutationResolver) ResumeStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	return r.StrategyService.ResumeStrategy(ctx, id)
}

// CloseStrategy is the resolver for the closeStrategy field.
func (r *mutationResolver) CloseStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	return r.StrategyService.CloseStrategy(ctx, id)
}

// DeleteStrategy is the resolver for the deleteStrategy field.
func (r *mutationResolver) DeleteStrategy(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.StrategyService.DeleteStrategy(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// BatchDeleteStrategies is the resolver for the batchDeleteStrategies field.
func (r *mutationResolver) BatchDeleteStrategies(ctx context.Context, ids []uuid.UUID) (int, error) {
	return r.StrategyService.BatchDeleteStrategies(ctx, ids)
}

// BatchPauseStrategies is the resolver for the batchPauseStrategies field.
func (r *mutationResolver) BatchPauseStrategies(ctx context.Context, ids []uuid.UUID) (int, error) {
	return r.StrategyService.BatchPauseStrategies(ctx, ids)
}

// BatchResumeStrategies is the resolver for the batchResumeStrategies field.
func (r *mutationResolver) BatchResumeStrategies(ctx context.Context, ids []uuid.UUID) (int, error) {
	return r.StrategyService.BatchResumeStrategies(ctx, ids)
}

// BatchCloseStrategies is the resolver for the batchCloseStrategies field.
func (r *mutationResolver) BatchCloseStrategies(ctx context.Context, ids []uuid.UUID) (int, error) {
	return r.StrategyService.BatchCloseStrategies(ctx, ids)
}

// Strategy is the resolver for the strategy field.
func (r *queryResolver) Strategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	return r.StrategyService.GetStrategyByID(ctx, id)
}

// UserStrategies is the resolver for the userStrategies field.
func (r *queryResolver) UserStrategies(ctx context.Context, userID uuid.UUID, scope *string, status *strategy.StrategyStatus, search *string, filters map[string]any, first *int, after *string, last *int, before *string) (*generated.StrategyConnection, error) {
	// Use scope parameter if provided, otherwise fall back to legacy status parameter
	effectiveScope := scope
	if effectiveScope == nil && status != nil {
		// Legacy support: map status to scope
		statusStr := string(*status)
		effectiveScope = &statusStr
	}

	// Get filtered strategies from service (uses SQL WHERE, not in-memory filtering)
	filtered, err := r.StrategyService.GetStrategiesWithScope(ctx, userID, effectiveScope, search, filters)
	if err != nil {
		return nil, fmt.Errorf("failed to get strategies: %w", err)
	}

	// Get scope counts from service (uses SQL GROUP BY)
	scopeCounts, err := r.StrategyService.GetStrategiesScopes(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get scope counts: %w", err)
	}

	// Apply pagination
	params := relay.PaginationParams{
		First:  first,
		After:  after,
		Last:   last,
		Before: before,
	}

	if err := params.Validate(); err != nil {
		return nil, fmt.Errorf("invalid pagination params: %w", err)
	}

	totalCount := len(filtered)
	offset, limit, err := relay.CalculateOffsetLimit(params, totalCount)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate pagination: %w", err)
	}

	// Apply offset and limit
	end := offset + limit
	if end > totalCount {
		end = totalCount
	}
	if offset > totalCount {
		offset = totalCount
	}

	items := filtered[offset:end]

	// Build connection with scopes and filters using helper
	return buildStrategyConnection(items, totalCount, params, offset, scopeCounts)
}

// Strategies is the resolver for the strategies field.
func (r *queryResolver) Strategies(ctx context.Context, scope *string, status *strategy.StrategyStatus, search *string, filters map[string]any, first *int, after *string, last *int, before *string) (*generated.StrategyConnection, error) {
	// Get current user from context (auth middleware)
	currentUser := middleware.UserFromContext(ctx)
	if currentUser == nil {
		return nil, fmt.Errorf("unauthorized: user not found in context")
	}

	// Use scope parameter if provided, otherwise fall back to legacy status parameter
	effectiveScope := scope
	if effectiveScope == nil && status != nil {
		// Legacy support: map status to scope
		statusStr := string(*status)
		effectiveScope = &statusStr
	}

	// Get filtered strategies from service (uses SQL WHERE, not in-memory filtering)
	filtered, err := r.StrategyService.GetStrategiesWithScope(ctx, currentUser.ID, effectiveScope, search, filters)
	if err != nil {
		return nil, fmt.Errorf("failed to get strategies: %w", err)
	}

	// Get scope counts from service (uses SQL GROUP BY)
	scopeCounts, err := r.StrategyService.GetStrategiesScopes(ctx, currentUser.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get scope counts: %w", err)
	}

	// Apply pagination
	params := relay.PaginationParams{
		First:  first,
		After:  after,
		Last:   last,
		Before: before,
	}

	if err := params.Validate(); err != nil {
		return nil, fmt.Errorf("invalid pagination params: %w", err)
	}

	totalCount := len(filtered)
	offset, limit, err := relay.CalculateOffsetLimit(params, totalCount)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate pagination: %w", err)
	}

	// Apply offset and limit
	end := offset + limit
	if end > totalCount {
		end = totalCount
	}
	if offset > totalCount {
		offset = totalCount
	}

	items := filtered[offset:end]

	// Build connection with scopes and filters using helper
	return buildStrategyConnection(items, totalCount, params, offset, scopeCounts)
}

// UserID is the resolver for the userID field.
func (r *strategyResolver) UserID(ctx context.Context, obj *strategy.Strategy) (uuid.UUID, error) {
	return obj.UserID, nil
}

// User is the resolver for the user field.
func (r *strategyResolver) User(ctx context.Context, obj *strategy.Strategy) (*user.User, error) {
	// Fetch related user
	return r.UserService.GetByID(ctx, obj.UserID)
}

// TargetAllocations is the resolver for the targetAllocations field.
func (r *strategyResolver) TargetAllocations(ctx context.Context, obj *strategy.Strategy) (map[string]any, error) {
	// Parse JSON target allocations
	if obj.TargetAllocations == nil {
		return nil, nil
	}

	var result map[string]interface{}
	if err := json.Unmarshal(obj.TargetAllocations, &result); err != nil {
		return nil, fmt.Errorf("failed to parse target allocations: %w", err)
	}

	return result, nil
}

// ReasoningLog is the resolver for the reasoningLog field.
func (r *strategyResolver) ReasoningLog(ctx context.Context, obj *strategy.Strategy) (map[string]any, error) {
	// Parse JSON reasoning log
	if obj.ReasoningLog == nil {
		return nil, nil
	}

	var result map[string]interface{}
	if err := json.Unmarshal(obj.ReasoningLog, &result); err != nil {
		return nil, fmt.Errorf("failed to parse reasoning log: %w", err)
	}

	return result, nil
}

// Strategy returns generated.StrategyResolver implementation.
func (r *Resolver) Strategy() generated.StrategyResolver { return &strategyResolver{r} }

type strategyResolver struct{ *Resolver }
