package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/json"
	"fmt"
	"prometheus/internal/api/graphql/generated"
	"prometheus/internal/domain/strategy"
	"prometheus/internal/domain/user"
	strategyService "prometheus/internal/services/strategy"

	"github.com/google/uuid"
)

// CreateStrategy is the resolver for the createStrategy field.
func (r *mutationResolver) CreateStrategy(ctx context.Context, userID uuid.UUID, input generated.CreateStrategyInput) (*strategy.Strategy, error) {
	params := strategyService.CreateStrategyParams{
		UserID:           userID,
		Name:             input.Name,
		Description:      input.Description,
		AllocatedCapital: input.AllocatedCapital,
		RiskTolerance:    input.RiskTolerance,
	}

	return r.StrategyService.CreateStrategy(ctx, params)
}

// UpdateStrategy is the resolver for the updateStrategy field.
func (r *mutationResolver) UpdateStrategy(ctx context.Context, id uuid.UUID, input generated.UpdateStrategyInput) (*strategy.Strategy, error) {
	// TODO: implement update strategy
	return nil, fmt.Errorf("UpdateStrategy not yet implemented")
}

// PauseStrategy is the resolver for the pauseStrategy field.
func (r *mutationResolver) PauseStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	// TODO: implement pause strategy
	return nil, fmt.Errorf("PauseStrategy not yet implemented")
}

// ResumeStrategy is the resolver for the resumeStrategy field.
func (r *mutationResolver) ResumeStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	// TODO: implement resume strategy
	return nil, fmt.Errorf("ResumeStrategy not yet implemented")
}

// CloseStrategy is the resolver for the closeStrategy field.
func (r *mutationResolver) CloseStrategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	// TODO: implement close strategy
	return nil, fmt.Errorf("CloseStrategy not yet implemented")
}

// Strategy is the resolver for the strategy field.
func (r *queryResolver) Strategy(ctx context.Context, id uuid.UUID) (*strategy.Strategy, error) {
	return r.StrategyService.GetStrategyByID(ctx, id)
}

// UserStrategies is the resolver for the userStrategies field.
func (r *queryResolver) UserStrategies(ctx context.Context, userID uuid.UUID, status *strategy.StrategyStatus) ([]*strategy.Strategy, error) {
	// Get active strategies for user
	strategies, err := r.StrategyService.GetActiveStrategies(ctx, userID)
	if err != nil {
		return nil, err
	}

	// Filter by status if provided
	if status != nil {
		filtered := make([]*strategy.Strategy, 0)
		for _, s := range strategies {
			if s.Status == *status {
				filtered = append(filtered, s)
			}
		}
		return filtered, nil
	}

	return strategies, nil
}

// Strategies is the resolver for the strategies field.
func (r *queryResolver) Strategies(ctx context.Context, limit *int, offset *int, status *strategy.StrategyStatus) ([]*strategy.Strategy, error) {
	// TODO: implement admin query for all strategies
	return nil, fmt.Errorf("Strategies admin query not yet implemented")
}

// UserID is the resolver for the userID field.
func (r *strategyResolver) UserID(ctx context.Context, obj *strategy.Strategy) (uuid.UUID, error) {
	return obj.UserID, nil
}

// User is the resolver for the user field.
func (r *strategyResolver) User(ctx context.Context, obj *strategy.Strategy) (*user.User, error) {
	// Fetch related user
	return r.UserService.GetByID(ctx, obj.UserID)
}

// TargetAllocations is the resolver for the targetAllocations field.
func (r *strategyResolver) TargetAllocations(ctx context.Context, obj *strategy.Strategy) (map[string]any, error) {
	// Parse JSON target allocations
	if obj.TargetAllocations == nil {
		return nil, nil
	}

	var result map[string]interface{}
	if err := json.Unmarshal(obj.TargetAllocations, &result); err != nil {
		return nil, fmt.Errorf("failed to parse target allocations: %w", err)
	}

	return result, nil
}

// ReasoningLog is the resolver for the reasoningLog field.
func (r *strategyResolver) ReasoningLog(ctx context.Context, obj *strategy.Strategy) (map[string]any, error) {
	// Parse JSON reasoning log
	if obj.ReasoningLog == nil {
		return nil, nil
	}

	var result map[string]interface{}
	if err := json.Unmarshal(obj.ReasoningLog, &result); err != nil {
		return nil, fmt.Errorf("failed to parse reasoning log: %w", err)
	}

	return result, nil
}

// Strategy returns generated.StrategyResolver implementation.
func (r *Resolver) Strategy() generated.StrategyResolver { return &strategyResolver{r} }

type strategyResolver struct{ *Resolver }
