// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: internal/events/proto/events.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseEvent contains common fields for all events
type BaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BaseEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BaseEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// OpportunityFoundEvent is published when a trading opportunity is detected
type OpportunityFoundEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`     // "long" or "short"
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 - 1.0
	Entry         float64                `protobuf:"fixed64,6,opt,name=entry,proto3" json:"entry,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,7,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfit    float64                `protobuf:"fixed64,8,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	Timeframe     string                 `protobuf:"bytes,9,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Strategy      string                 `protobuf:"bytes,10,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Reasoning     string                 `protobuf:"bytes,11,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Indicators    map[string]string      `protobuf:"bytes,12,rep,name=indicators,proto3" json:"indicators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpportunityFoundEvent) Reset() {
	*x = OpportunityFoundEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpportunityFoundEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpportunityFoundEvent) ProtoMessage() {}

func (x *OpportunityFoundEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpportunityFoundEvent.ProtoReflect.Descriptor instead.
func (*OpportunityFoundEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *OpportunityFoundEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OpportunityFoundEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OpportunityFoundEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OpportunityFoundEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OpportunityFoundEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OpportunityFoundEvent) GetEntry() float64 {
	if x != nil {
		return x.Entry
	}
	return 0
}

func (x *OpportunityFoundEvent) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *OpportunityFoundEvent) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *OpportunityFoundEvent) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *OpportunityFoundEvent) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *OpportunityFoundEvent) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *OpportunityFoundEvent) GetIndicators() map[string]string {
	if x != nil {
		return x.Indicators
	}
	return nil
}

// RegimeChangedEvent is published when market regime changes
type RegimeChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OldRegime     string                 `protobuf:"bytes,3,opt,name=old_regime,json=oldRegime,proto3" json:"old_regime,omitempty"`
	NewRegime     string                 `protobuf:"bytes,4,opt,name=new_regime,json=newRegime,proto3" json:"new_regime,omitempty"` // "trending", "ranging", "volatile"
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Volatility    float64                `protobuf:"fixed64,6,opt,name=volatility,proto3" json:"volatility,omitempty"`
	Trend         string                 `protobuf:"bytes,7,opt,name=trend,proto3" json:"trend,omitempty"` // "bullish", "bearish", "neutral"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegimeChangedEvent) Reset() {
	*x = RegimeChangedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegimeChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegimeChangedEvent) ProtoMessage() {}

func (x *RegimeChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegimeChangedEvent.ProtoReflect.Descriptor instead.
func (*RegimeChangedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *RegimeChangedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegimeChangedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegimeChangedEvent) GetOldRegime() string {
	if x != nil {
		return x.OldRegime
	}
	return ""
}

func (x *RegimeChangedEvent) GetNewRegime() string {
	if x != nil {
		return x.NewRegime
	}
	return ""
}

func (x *RegimeChangedEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RegimeChangedEvent) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *RegimeChangedEvent) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

// OrderPlacedEvent is published when an order is placed
type OrderPlacedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Side          string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"` // "buy" or "sell"
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // "market", "limit", "stop"
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	AgentId       string                 `protobuf:"bytes,9,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,10,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPlacedEvent) Reset() {
	*x = OrderPlacedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPlacedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent) ProtoMessage() {}

func (x *OrderPlacedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPlacedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrderPlacedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPlacedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderPlacedEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderPlacedEvent) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderPlacedEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderPlacedEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderPlacedEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPlacedEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OrderPlacedEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// OrderFilledEvent is published when an order is filled
type OrderFilledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Side          string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	FilledPrice   float64                `protobuf:"fixed64,6,opt,name=filled_price,json=filledPrice,proto3" json:"filled_price,omitempty"`
	FilledAmount  float64                `protobuf:"fixed64,7,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	Fee           float64                `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeCurrency   string                 `protobuf:"bytes,9,opt,name=fee_currency,json=feeCurrency,proto3" json:"fee_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFilledEvent) Reset() {
	*x = OrderFilledEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFilledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFilledEvent) ProtoMessage() {}

func (x *OrderFilledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFilledEvent.ProtoReflect.Descriptor instead.
func (*OrderFilledEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderFilledEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrderFilledEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderFilledEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderFilledEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderFilledEvent) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderFilledEvent) GetFilledPrice() float64 {
	if x != nil {
		return x.FilledPrice
	}
	return 0
}

func (x *OrderFilledEvent) GetFilledAmount() float64 {
	if x != nil {
		return x.FilledAmount
	}
	return 0
}

func (x *OrderFilledEvent) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderFilledEvent) GetFeeCurrency() string {
	if x != nil {
		return x.FeeCurrency
	}
	return ""
}

// PositionOpenedEvent is published when a position is opened
type PositionOpenedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PositionId    string                 `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Side          string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Leverage      float64                `protobuf:"fixed64,8,opt,name=leverage,proto3" json:"leverage,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,9,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfit    float64                `protobuf:"fixed64,10,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	StrategyId    string                 `protobuf:"bytes,11,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionOpenedEvent) Reset() {
	*x = PositionOpenedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionOpenedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionOpenedEvent) ProtoMessage() {}

func (x *PositionOpenedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionOpenedEvent.ProtoReflect.Descriptor instead.
func (*PositionOpenedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *PositionOpenedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PositionOpenedEvent) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PositionOpenedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionOpenedEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PositionOpenedEvent) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PositionOpenedEvent) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *PositionOpenedEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PositionOpenedEvent) GetLeverage() float64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *PositionOpenedEvent) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *PositionOpenedEvent) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *PositionOpenedEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// PositionClosedEvent is published when a position is closed
type PositionClosedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PositionId      string                 `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Symbol          string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange        string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Side            string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	EntryPrice      float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitPrice       float64                `protobuf:"fixed64,7,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	Amount          float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Pnl             float64                `protobuf:"fixed64,9,opt,name=pnl,proto3" json:"pnl,omitempty"`
	PnlPercent      float64                `protobuf:"fixed64,10,opt,name=pnl_percent,json=pnlPercent,proto3" json:"pnl_percent,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,11,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CloseReason     string                 `protobuf:"bytes,12,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"` // "take_profit", "stop_loss", "manual", "timeout"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PositionClosedEvent) Reset() {
	*x = PositionClosedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionClosedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionClosedEvent) ProtoMessage() {}

func (x *PositionClosedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionClosedEvent.ProtoReflect.Descriptor instead.
func (*PositionClosedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *PositionClosedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PositionClosedEvent) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PositionClosedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionClosedEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PositionClosedEvent) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PositionClosedEvent) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *PositionClosedEvent) GetExitPrice() float64 {
	if x != nil {
		return x.ExitPrice
	}
	return 0
}

func (x *PositionClosedEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PositionClosedEvent) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *PositionClosedEvent) GetPnlPercent() float64 {
	if x != nil {
		return x.PnlPercent
	}
	return 0
}

func (x *PositionClosedEvent) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *PositionClosedEvent) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

// CircuitBreakerTrippedEvent is published when circuit breaker is activated
type CircuitBreakerTrippedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CurrentLoss   float64                `protobuf:"fixed64,3,opt,name=current_loss,json=currentLoss,proto3" json:"current_loss,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Drawdown      float64                `protobuf:"fixed64,5,opt,name=drawdown,proto3" json:"drawdown,omitempty"`
	AutoResume    bool                   `protobuf:"varint,6,opt,name=auto_resume,json=autoResume,proto3" json:"auto_resume,omitempty"`
	ResumeAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=resume_at,json=resumeAt,proto3" json:"resume_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitBreakerTrippedEvent) Reset() {
	*x = CircuitBreakerTrippedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerTrippedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerTrippedEvent) ProtoMessage() {}

func (x *CircuitBreakerTrippedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerTrippedEvent.ProtoReflect.Descriptor instead.
func (*CircuitBreakerTrippedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *CircuitBreakerTrippedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CircuitBreakerTrippedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CircuitBreakerTrippedEvent) GetCurrentLoss() float64 {
	if x != nil {
		return x.CurrentLoss
	}
	return 0
}

func (x *CircuitBreakerTrippedEvent) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CircuitBreakerTrippedEvent) GetDrawdown() float64 {
	if x != nil {
		return x.Drawdown
	}
	return 0
}

func (x *CircuitBreakerTrippedEvent) GetAutoResume() bool {
	if x != nil {
		return x.AutoResume
	}
	return false
}

func (x *CircuitBreakerTrippedEvent) GetResumeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResumeAt
	}
	return nil
}

// AgentExecutedEvent is published after agent execution
type AgentExecutedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,6,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Decision      string                 `protobuf:"bytes,9,opt,name=decision,proto3" json:"decision,omitempty"`
	Confidence    float64                `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExecutedEvent) Reset() {
	*x = AgentExecutedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExecutedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExecutedEvent) ProtoMessage() {}

func (x *AgentExecutedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExecutedEvent.ProtoReflect.Descriptor instead.
func (*AgentExecutedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *AgentExecutedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AgentExecutedEvent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentExecutedEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentExecutedEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AgentExecutedEvent) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *AgentExecutedEvent) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *AgentExecutedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentExecutedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentExecutedEvent) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *AgentExecutedEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// DecisionMadeEvent is published when agent makes a decision
type DecisionMadeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "buy", "sell", "hold", "close"
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning     string                 `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Context       map[string]string      `protobuf:"bytes,8,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionMadeEvent) Reset() {
	*x = DecisionMadeEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionMadeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionMadeEvent) ProtoMessage() {}

func (x *DecisionMadeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionMadeEvent.ProtoReflect.Descriptor instead.
func (*DecisionMadeEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *DecisionMadeEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DecisionMadeEvent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *DecisionMadeEvent) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *DecisionMadeEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DecisionMadeEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DecisionMadeEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionMadeEvent) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *DecisionMadeEvent) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// WorkerFailedEvent is published when a worker fails
type WorkerFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	WorkerName    string                 `protobuf:"bytes,2,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FailCount     int32                  `protobuf:"varint,4,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	LastSuccess   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerFailedEvent) Reset() {
	*x = WorkerFailedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerFailedEvent) ProtoMessage() {}

func (x *WorkerFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerFailedEvent.ProtoReflect.Descriptor instead.
func (*WorkerFailedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerFailedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *WorkerFailedEvent) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *WorkerFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkerFailedEvent) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *WorkerFailedEvent) GetLastSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

// DrawdownAlert is published when user approaches drawdown limit
type DrawdownAlert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CurrentDrawdown float64                `protobuf:"fixed64,3,opt,name=current_drawdown,json=currentDrawdown,proto3" json:"current_drawdown,omitempty"`
	MaxDrawdown     float64                `protobuf:"fixed64,4,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	Percentage      float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	DailyPnl        float64                `protobuf:"fixed64,6,opt,name=daily_pnl,json=dailyPnl,proto3" json:"daily_pnl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DrawdownAlert) Reset() {
	*x = DrawdownAlert{}
	mi := &file_internal_events_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawdownAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawdownAlert) ProtoMessage() {}

func (x *DrawdownAlert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawdownAlert.ProtoReflect.Descriptor instead.
func (*DrawdownAlert) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *DrawdownAlert) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DrawdownAlert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DrawdownAlert) GetCurrentDrawdown() float64 {
	if x != nil {
		return x.CurrentDrawdown
	}
	return 0
}

func (x *DrawdownAlert) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *DrawdownAlert) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *DrawdownAlert) GetDailyPnl() float64 {
	if x != nil {
		return x.DailyPnl
	}
	return 0
}

// ConsecutiveLossesAlert is published when user has multiple consecutive losses
type ConsecutiveLossesAlert struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Base              *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ConsecutiveLosses int32                  `protobuf:"varint,2,opt,name=consecutive_losses,json=consecutiveLosses,proto3" json:"consecutive_losses,omitempty"`
	MaxAllowed        int32                  `protobuf:"varint,3,opt,name=max_allowed,json=maxAllowed,proto3" json:"max_allowed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsecutiveLossesAlert) Reset() {
	*x = ConsecutiveLossesAlert{}
	mi := &file_internal_events_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsecutiveLossesAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsecutiveLossesAlert) ProtoMessage() {}

func (x *ConsecutiveLossesAlert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsecutiveLossesAlert.ProtoReflect.Descriptor instead.
func (*ConsecutiveLossesAlert) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *ConsecutiveLossesAlert) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConsecutiveLossesAlert) GetConsecutiveLosses() int32 {
	if x != nil {
		return x.ConsecutiveLosses
	}
	return 0
}

func (x *ConsecutiveLossesAlert) GetMaxAllowed() int32 {
	if x != nil {
		return x.MaxAllowed
	}
	return 0
}

// PnLUpdatedEvent is published when user PnL is recalculated
type PnLUpdatedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DailyPnl        float64                `protobuf:"fixed64,2,opt,name=daily_pnl,json=dailyPnl,proto3" json:"daily_pnl,omitempty"`
	DailyPnlPercent float64                `protobuf:"fixed64,3,opt,name=daily_pnl_percent,json=dailyPnlPercent,proto3" json:"daily_pnl_percent,omitempty"`
	TotalPnl        float64                `protobuf:"fixed64,4,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	TradesCount     int32                  `protobuf:"varint,5,opt,name=trades_count,json=tradesCount,proto3" json:"trades_count,omitempty"`
	WinningTrades   int32                  `protobuf:"varint,6,opt,name=winning_trades,json=winningTrades,proto3" json:"winning_trades,omitempty"`
	LosingTrades    int32                  `protobuf:"varint,7,opt,name=losing_trades,json=losingTrades,proto3" json:"losing_trades,omitempty"`
	WinRate         float64                `protobuf:"fixed64,8,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PnLUpdatedEvent) Reset() {
	*x = PnLUpdatedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnLUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnLUpdatedEvent) ProtoMessage() {}

func (x *PnLUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnLUpdatedEvent.ProtoReflect.Descriptor instead.
func (*PnLUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *PnLUpdatedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PnLUpdatedEvent) GetDailyPnl() float64 {
	if x != nil {
		return x.DailyPnl
	}
	return 0
}

func (x *PnLUpdatedEvent) GetDailyPnlPercent() float64 {
	if x != nil {
		return x.DailyPnlPercent
	}
	return 0
}

func (x *PnLUpdatedEvent) GetTotalPnl() float64 {
	if x != nil {
		return x.TotalPnl
	}
	return 0
}

func (x *PnLUpdatedEvent) GetTradesCount() int32 {
	if x != nil {
		return x.TradesCount
	}
	return 0
}

func (x *PnLUpdatedEvent) GetWinningTrades() int32 {
	if x != nil {
		return x.WinningTrades
	}
	return 0
}

func (x *PnLUpdatedEvent) GetLosingTrades() int32 {
	if x != nil {
		return x.LosingTrades
	}
	return 0
}

func (x *PnLUpdatedEvent) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

// JournalEntryCreatedEvent is published when a journal entry is created
type JournalEntryCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	EntryId       string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Pnl           float64                `protobuf:"fixed64,5,opt,name=pnl,proto3" json:"pnl,omitempty"`
	PnlPercent    float64                `protobuf:"fixed64,6,opt,name=pnl_percent,json=pnlPercent,proto3" json:"pnl_percent,omitempty"`
	LessonLearned string                 `protobuf:"bytes,7,opt,name=lesson_learned,json=lessonLearned,proto3" json:"lesson_learned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntryCreatedEvent) Reset() {
	*x = JournalEntryCreatedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntryCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntryCreatedEvent) ProtoMessage() {}

func (x *JournalEntryCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntryCreatedEvent.ProtoReflect.Descriptor instead.
func (*JournalEntryCreatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *JournalEntryCreatedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *JournalEntryCreatedEvent) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *JournalEntryCreatedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *JournalEntryCreatedEvent) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *JournalEntryCreatedEvent) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *JournalEntryCreatedEvent) GetPnlPercent() float64 {
	if x != nil {
		return x.PnlPercent
	}
	return 0
}

func (x *JournalEntryCreatedEvent) GetLessonLearned() string {
	if x != nil {
		return x.LessonLearned
	}
	return ""
}

// DailyReportEvent is published with daily performance summary
type DailyReportEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DailyPnl        float64                `protobuf:"fixed64,2,opt,name=daily_pnl,json=dailyPnl,proto3" json:"daily_pnl,omitempty"`
	DailyPnlPercent float64                `protobuf:"fixed64,3,opt,name=daily_pnl_percent,json=dailyPnlPercent,proto3" json:"daily_pnl_percent,omitempty"`
	TotalTrades     int32                  `protobuf:"varint,4,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	WinningTrades   int32                  `protobuf:"varint,5,opt,name=winning_trades,json=winningTrades,proto3" json:"winning_trades,omitempty"`
	WinRate         float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	SharpeRatio     float64                `protobuf:"fixed64,7,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	MaxDrawdown     float64                `protobuf:"fixed64,8,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyReportEvent) Reset() {
	*x = DailyReportEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportEvent) ProtoMessage() {}

func (x *DailyReportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportEvent.ProtoReflect.Descriptor instead.
func (*DailyReportEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *DailyReportEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DailyReportEvent) GetDailyPnl() float64 {
	if x != nil {
		return x.DailyPnl
	}
	return 0
}

func (x *DailyReportEvent) GetDailyPnlPercent() float64 {
	if x != nil {
		return x.DailyPnlPercent
	}
	return 0
}

func (x *DailyReportEvent) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

func (x *DailyReportEvent) GetWinningTrades() int32 {
	if x != nil {
		return x.WinningTrades
	}
	return 0
}

func (x *DailyReportEvent) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *DailyReportEvent) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *DailyReportEvent) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

// StrategyDisabledEvent is published when a strategy is auto-disabled
type StrategyDisabledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	StrategyName  string                 `protobuf:"bytes,3,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	WinRate       float64                `protobuf:"fixed64,5,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	ProfitFactor  float64                `protobuf:"fixed64,6,opt,name=profit_factor,json=profitFactor,proto3" json:"profit_factor,omitempty"`
	TotalTrades   int32                  `protobuf:"varint,7,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyDisabledEvent) Reset() {
	*x = StrategyDisabledEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyDisabledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyDisabledEvent) ProtoMessage() {}

func (x *StrategyDisabledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyDisabledEvent.ProtoReflect.Descriptor instead.
func (*StrategyDisabledEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *StrategyDisabledEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *StrategyDisabledEvent) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyDisabledEvent) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *StrategyDisabledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StrategyDisabledEvent) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *StrategyDisabledEvent) GetProfitFactor() float64 {
	if x != nil {
		return x.ProfitFactor
	}
	return 0
}

func (x *StrategyDisabledEvent) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

// OrderCancelledEvent is published when an order is cancelled
type OrderCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelledEvent) Reset() {
	*x = OrderCancelledEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledEvent) ProtoMessage() {}

func (x *OrderCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledEvent.ProtoReflect.Descriptor instead.
func (*OrderCancelledEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *OrderCancelledEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrderCancelledEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderCancelledEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderCancelledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PositionPnLUpdatedEvent is published when position PnL is updated
type PositionPnLUpdatedEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Base                 *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PositionId           string                 `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Symbol               string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UnrealizedPnl        float64                `protobuf:"fixed64,4,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	UnrealizedPnlPercent float64                `protobuf:"fixed64,5,opt,name=unrealized_pnl_percent,json=unrealizedPnlPercent,proto3" json:"unrealized_pnl_percent,omitempty"`
	CurrentPrice         float64                `protobuf:"fixed64,6,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	EntryPrice           float64                `protobuf:"fixed64,7,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PositionPnLUpdatedEvent) Reset() {
	*x = PositionPnLUpdatedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionPnLUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionPnLUpdatedEvent) ProtoMessage() {}

func (x *PositionPnLUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionPnLUpdatedEvent.ProtoReflect.Descriptor instead.
func (*PositionPnLUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *PositionPnLUpdatedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PositionPnLUpdatedEvent) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PositionPnLUpdatedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionPnLUpdatedEvent) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *PositionPnLUpdatedEvent) GetUnrealizedPnlPercent() float64 {
	if x != nil {
		return x.UnrealizedPnlPercent
	}
	return 0
}

func (x *PositionPnLUpdatedEvent) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *PositionPnLUpdatedEvent) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

// FVGDetectedEvent is published when Fair Value Gap is detected
type FVGDetectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // bullish, bearish
	TopPrice      float64                `protobuf:"fixed64,4,opt,name=top_price,json=topPrice,proto3" json:"top_price,omitempty"`
	BottomPrice   float64                `protobuf:"fixed64,5,opt,name=bottom_price,json=bottomPrice,proto3" json:"bottom_price,omitempty"`
	GapPercent    float64                `protobuf:"fixed64,6,opt,name=gap_percent,json=gapPercent,proto3" json:"gap_percent,omitempty"`
	Filled        bool                   `protobuf:"varint,7,opt,name=filled,proto3" json:"filled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FVGDetectedEvent) Reset() {
	*x = FVGDetectedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FVGDetectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FVGDetectedEvent) ProtoMessage() {}

func (x *FVGDetectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FVGDetectedEvent.ProtoReflect.Descriptor instead.
func (*FVGDetectedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{19}
}

func (x *FVGDetectedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FVGDetectedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FVGDetectedEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FVGDetectedEvent) GetTopPrice() float64 {
	if x != nil {
		return x.TopPrice
	}
	return 0
}

func (x *FVGDetectedEvent) GetBottomPrice() float64 {
	if x != nil {
		return x.BottomPrice
	}
	return 0
}

func (x *FVGDetectedEvent) GetGapPercent() float64 {
	if x != nil {
		return x.GapPercent
	}
	return 0
}

func (x *FVGDetectedEvent) GetFilled() bool {
	if x != nil {
		return x.Filled
	}
	return false
}

// OrderBlockDetectedEvent is published when Order Block is detected
type OrderBlockDetectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // bullish, bearish
	TopPrice      float64                `protobuf:"fixed64,4,opt,name=top_price,json=topPrice,proto3" json:"top_price,omitempty"`
	BottomPrice   float64                `protobuf:"fixed64,5,opt,name=bottom_price,json=bottomPrice,proto3" json:"bottom_price,omitempty"`
	Strength      float64                `protobuf:"fixed64,6,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBlockDetectedEvent) Reset() {
	*x = OrderBlockDetectedEvent{}
	mi := &file_internal_events_proto_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBlockDetectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBlockDetectedEvent) ProtoMessage() {}

func (x *OrderBlockDetectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_events_proto_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBlockDetectedEvent.ProtoReflect.Descriptor instead.
func (*OrderBlockDetectedEvent) Descriptor() ([]byte, []int) {
	return file_internal_events_proto_events_proto_rawDescGZIP(), []int{20}
}

func (x *OrderBlockDetectedEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrderBlockDetectedEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBlockDetectedEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderBlockDetectedEvent) GetTopPrice() float64 {
	if x != nil {
		return x.TopPrice
	}
	return 0
}

func (x *OrderBlockDetectedEvent) GetBottomPrice() float64 {
	if x != nil {
		return x.BottomPrice
	}
	return 0
}

func (x *OrderBlockDetectedEvent) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

var File_internal_events_proto_events_proto protoreflect.FileDescriptor

const file_internal_events_proto_events_proto_rawDesc = "" +
	"\n" +
	"\"internal/events/proto/events.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\tBaseEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xea\x03\n" +
	"\x15OpportunityFoundEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05entry\x18\x06 \x01(\x01R\x05entry\x12\x1b\n" +
	"\tstop_loss\x18\a \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\b \x01(\x01R\n" +
	"takeProfit\x12\x1c\n" +
	"\ttimeframe\x18\t \x01(\tR\ttimeframe\x12\x1a\n" +
	"\bstrategy\x18\n" +
	" \x01(\tR\bstrategy\x12\x1c\n" +
	"\treasoning\x18\v \x01(\tR\treasoning\x12M\n" +
	"\n" +
	"indicators\x18\f \x03(\v2-.events.OpportunityFoundEvent.IndicatorsEntryR\n" +
	"indicators\x1a=\n" +
	"\x0fIndicatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x12RegimeChangedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"old_regime\x18\x03 \x01(\tR\toldRegime\x12\x1d\n" +
	"\n" +
	"new_regime\x18\x04 \x01(\tR\tnewRegime\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"volatility\x18\x06 \x01(\x01R\n" +
	"volatility\x12\x14\n" +
	"\x05trend\x18\a \x01(\tR\x05trend\"\x9a\x02\n" +
	"\x10OrderPlacedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x19\n" +
	"\bagent_id\x18\t \x01(\tR\aagentId\x12\x1f\n" +
	"\vstrategy_id\x18\n" +
	" \x01(\tR\n" +
	"strategyId\"\x99\x02\n" +
	"\x10OrderFilledEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12!\n" +
	"\ffilled_price\x18\x06 \x01(\x01R\vfilledPrice\x12#\n" +
	"\rfilled_amount\x18\a \x01(\x01R\ffilledAmount\x12\x10\n" +
	"\x03fee\x18\b \x01(\x01R\x03fee\x12!\n" +
	"\ffee_currency\x18\t \x01(\tR\vfeeCurrency\"\xd9\x02\n" +
	"\x13PositionOpenedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1a\n" +
	"\bleverage\x18\b \x01(\x01R\bleverage\x12\x1b\n" +
	"\tstop_loss\x18\t \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\n" +
	" \x01(\x01R\n" +
	"takeProfit\x12\x1f\n" +
	"\vstrategy_id\x18\v \x01(\tR\n" +
	"strategyId\"\xfe\x02\n" +
	"\x13PositionClosedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"exit_price\x18\a \x01(\x01R\texitPrice\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x10\n" +
	"\x03pnl\x18\t \x01(\x01R\x03pnl\x12\x1f\n" +
	"\vpnl_percent\x18\n" +
	" \x01(\x01R\n" +
	"pnlPercent\x12)\n" +
	"\x10duration_seconds\x18\v \x01(\x03R\x0fdurationSeconds\x12!\n" +
	"\fclose_reason\x18\f \x01(\tR\vcloseReason\"\x92\x02\n" +
	"\x1aCircuitBreakerTrippedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fcurrent_loss\x18\x03 \x01(\x01R\vcurrentLoss\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12\x1a\n" +
	"\bdrawdown\x18\x05 \x01(\x01R\bdrawdown\x12\x1f\n" +
	"\vauto_resume\x18\x06 \x01(\bR\n" +
	"autoResume\x127\n" +
	"\tresume_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bresumeAt\"\xb9\x02\n" +
	"\x12AgentExecutedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12\x19\n" +
	"\bcost_usd\x18\x06 \x01(\x01R\acostUsd\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1a\n" +
	"\bdecision\x18\t \x01(\tR\bdecision\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\"\xe1\x02\n" +
	"\x11DecisionMadeEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12@\n" +
	"\acontext\x18\b \x03(\v2&.events.DecisionMadeEvent.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x11WorkerFailedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1f\n" +
	"\vworker_name\x18\x02 \x01(\tR\n" +
	"workerName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x04 \x01(\x05R\tfailCount\x12=\n" +
	"\flast_success\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastSuccess\"\xd9\x01\n" +
	"\rDrawdownAlert\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10current_drawdown\x18\x03 \x01(\x01R\x0fcurrentDrawdown\x12!\n" +
	"\fmax_drawdown\x18\x04 \x01(\x01R\vmaxDrawdown\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\x12\x1b\n" +
	"\tdaily_pnl\x18\x06 \x01(\x01R\bdailyPnl\"\x8f\x01\n" +
	"\x16ConsecutiveLossesAlert\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12-\n" +
	"\x12consecutive_losses\x18\x02 \x01(\x05R\x11consecutiveLosses\x12\x1f\n" +
	"\vmax_allowed\x18\x03 \x01(\x05R\n" +
	"maxAllowed\"\xa8\x02\n" +
	"\x0fPnLUpdatedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1b\n" +
	"\tdaily_pnl\x18\x02 \x01(\x01R\bdailyPnl\x12*\n" +
	"\x11daily_pnl_percent\x18\x03 \x01(\x01R\x0fdailyPnlPercent\x12\x1b\n" +
	"\ttotal_pnl\x18\x04 \x01(\x01R\btotalPnl\x12!\n" +
	"\ftrades_count\x18\x05 \x01(\x05R\vtradesCount\x12%\n" +
	"\x0ewinning_trades\x18\x06 \x01(\x05R\rwinningTrades\x12#\n" +
	"\rlosing_trades\x18\a \x01(\x05R\flosingTrades\x12\x19\n" +
	"\bwin_rate\x18\b \x01(\x01R\awinRate\"\xe2\x01\n" +
	"\x18JournalEntryCreatedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x10\n" +
	"\x03pnl\x18\x05 \x01(\x01R\x03pnl\x12\x1f\n" +
	"\vpnl_percent\x18\x06 \x01(\x01R\n" +
	"pnlPercent\x12%\n" +
	"\x0elesson_learned\x18\a \x01(\tR\rlessonLearned\"\xad\x02\n" +
	"\x10DailyReportEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1b\n" +
	"\tdaily_pnl\x18\x02 \x01(\x01R\bdailyPnl\x12*\n" +
	"\x11daily_pnl_percent\x18\x03 \x01(\x01R\x0fdailyPnlPercent\x12!\n" +
	"\ftotal_trades\x18\x04 \x01(\x05R\vtotalTrades\x12%\n" +
	"\x0ewinning_trades\x18\x05 \x01(\x05R\rwinningTrades\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\x12!\n" +
	"\fsharpe_ratio\x18\a \x01(\x01R\vsharpeRatio\x12!\n" +
	"\fmax_drawdown\x18\b \x01(\x01R\vmaxDrawdown\"\xff\x01\n" +
	"\x15StrategyDisabledEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\tR\n" +
	"strategyId\x12#\n" +
	"\rstrategy_name\x18\x03 \x01(\tR\fstrategyName\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\bwin_rate\x18\x05 \x01(\x01R\awinRate\x12#\n" +
	"\rprofit_factor\x18\x06 \x01(\x01R\fprofitFactor\x12!\n" +
	"\ftotal_trades\x18\a \x01(\x05R\vtotalTrades\"\xa3\x01\n" +
	"\x13OrderCancelledEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x9c\x02\n" +
	"\x17PositionPnLUpdatedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x0eunrealized_pnl\x18\x04 \x01(\x01R\runrealizedPnl\x124\n" +
	"\x16unrealized_pnl_percent\x18\x05 \x01(\x01R\x14unrealizedPnlPercent\x12#\n" +
	"\rcurrent_price\x18\x06 \x01(\x01R\fcurrentPrice\x12\x1f\n" +
	"\ventry_price\x18\a \x01(\x01R\n" +
	"entryPrice\"\xde\x01\n" +
	"\x10FVGDetectedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\ttop_price\x18\x04 \x01(\x01R\btopPrice\x12!\n" +
	"\fbottom_price\x18\x05 \x01(\x01R\vbottomPrice\x12\x1f\n" +
	"\vgap_percent\x18\x06 \x01(\x01R\n" +
	"gapPercent\x12\x16\n" +
	"\x06filled\x18\a \x01(\bR\x06filled\"\xc8\x01\n" +
	"\x17OrderBlockDetectedEvent\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.events.BaseEventR\x04base\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\ttop_price\x18\x04 \x01(\x01R\btopPrice\x12!\n" +
	"\fbottom_price\x18\x05 \x01(\x01R\vbottomPrice\x12\x1a\n" +
	"\bstrength\x18\x06 \x01(\x01R\bstrengthB+Z)prometheus/internal/events/proto;eventspbb\x06proto3"

var (
	file_internal_events_proto_events_proto_rawDescOnce sync.Once
	file_internal_events_proto_events_proto_rawDescData []byte
)

func file_internal_events_proto_events_proto_rawDescGZIP() []byte {
	file_internal_events_proto_events_proto_rawDescOnce.Do(func() {
		file_internal_events_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_events_proto_events_proto_rawDesc), len(file_internal_events_proto_events_proto_rawDesc)))
	})
	return file_internal_events_proto_events_proto_rawDescData
}

var file_internal_events_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_events_proto_events_proto_goTypes = []any{
	(*BaseEvent)(nil),                  // 0: events.BaseEvent
	(*OpportunityFoundEvent)(nil),      // 1: events.OpportunityFoundEvent
	(*RegimeChangedEvent)(nil),         // 2: events.RegimeChangedEvent
	(*OrderPlacedEvent)(nil),           // 3: events.OrderPlacedEvent
	(*OrderFilledEvent)(nil),           // 4: events.OrderFilledEvent
	(*PositionOpenedEvent)(nil),        // 5: events.PositionOpenedEvent
	(*PositionClosedEvent)(nil),        // 6: events.PositionClosedEvent
	(*CircuitBreakerTrippedEvent)(nil), // 7: events.CircuitBreakerTrippedEvent
	(*AgentExecutedEvent)(nil),         // 8: events.AgentExecutedEvent
	(*DecisionMadeEvent)(nil),          // 9: events.DecisionMadeEvent
	(*WorkerFailedEvent)(nil),          // 10: events.WorkerFailedEvent
	(*DrawdownAlert)(nil),              // 11: events.DrawdownAlert
	(*ConsecutiveLossesAlert)(nil),     // 12: events.ConsecutiveLossesAlert
	(*PnLUpdatedEvent)(nil),            // 13: events.PnLUpdatedEvent
	(*JournalEntryCreatedEvent)(nil),   // 14: events.JournalEntryCreatedEvent
	(*DailyReportEvent)(nil),           // 15: events.DailyReportEvent
	(*StrategyDisabledEvent)(nil),      // 16: events.StrategyDisabledEvent
	(*OrderCancelledEvent)(nil),        // 17: events.OrderCancelledEvent
	(*PositionPnLUpdatedEvent)(nil),    // 18: events.PositionPnLUpdatedEvent
	(*FVGDetectedEvent)(nil),           // 19: events.FVGDetectedEvent
	(*OrderBlockDetectedEvent)(nil),    // 20: events.OrderBlockDetectedEvent
	nil,                                // 21: events.OpportunityFoundEvent.IndicatorsEntry
	nil,                                // 22: events.DecisionMadeEvent.ContextEntry
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_internal_events_proto_events_proto_depIdxs = []int32{
	23, // 0: events.BaseEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: events.OpportunityFoundEvent.base:type_name -> events.BaseEvent
	21, // 2: events.OpportunityFoundEvent.indicators:type_name -> events.OpportunityFoundEvent.IndicatorsEntry
	0,  // 3: events.RegimeChangedEvent.base:type_name -> events.BaseEvent
	0,  // 4: events.OrderPlacedEvent.base:type_name -> events.BaseEvent
	0,  // 5: events.OrderFilledEvent.base:type_name -> events.BaseEvent
	0,  // 6: events.PositionOpenedEvent.base:type_name -> events.BaseEvent
	0,  // 7: events.PositionClosedEvent.base:type_name -> events.BaseEvent
	0,  // 8: events.CircuitBreakerTrippedEvent.base:type_name -> events.BaseEvent
	23, // 9: events.CircuitBreakerTrippedEvent.resume_at:type_name -> google.protobuf.Timestamp
	0,  // 10: events.AgentExecutedEvent.base:type_name -> events.BaseEvent
	0,  // 11: events.DecisionMadeEvent.base:type_name -> events.BaseEvent
	22, // 12: events.DecisionMadeEvent.context:type_name -> events.DecisionMadeEvent.ContextEntry
	0,  // 13: events.WorkerFailedEvent.base:type_name -> events.BaseEvent
	23, // 14: events.WorkerFailedEvent.last_success:type_name -> google.protobuf.Timestamp
	0,  // 15: events.DrawdownAlert.base:type_name -> events.BaseEvent
	0,  // 16: events.ConsecutiveLossesAlert.base:type_name -> events.BaseEvent
	0,  // 17: events.PnLUpdatedEvent.base:type_name -> events.BaseEvent
	0,  // 18: events.JournalEntryCreatedEvent.base:type_name -> events.BaseEvent
	0,  // 19: events.DailyReportEvent.base:type_name -> events.BaseEvent
	0,  // 20: events.StrategyDisabledEvent.base:type_name -> events.BaseEvent
	0,  // 21: events.OrderCancelledEvent.base:type_name -> events.BaseEvent
	0,  // 22: events.PositionPnLUpdatedEvent.base:type_name -> events.BaseEvent
	0,  // 23: events.FVGDetectedEvent.base:type_name -> events.BaseEvent
	0,  // 24: events.OrderBlockDetectedEvent.base:type_name -> events.BaseEvent
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_events_proto_events_proto_init() }
func file_internal_events_proto_events_proto_init() {
	if File_internal_events_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_events_proto_events_proto_rawDesc), len(file_internal_events_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_events_proto_events_proto_goTypes,
		DependencyIndexes: file_internal_events_proto_events_proto_depIdxs,
		MessageInfos:      file_internal_events_proto_events_proto_msgTypes,
	}.Build()
	File_internal_events_proto_events_proto = out.File
	file_internal_events_proto_events_proto_goTypes = nil
	file_internal_events_proto_events_proto_depIdxs = nil
}
